apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.fullname" . }}-core
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    {{- include "harbor.selectorLabels" . | nindent 4 }}
    component: core
