{{- if eq .Values.expose.type "ingress" }}
{{- $ingress := .Values.expose.ingress -}}
{{- $tls := .Values.expose.tls -}}

{{- /* Set paths and pathType based on ingress controller */}}
{{- if eq $ingress.controller "gce" }}
  {{- $_ := set . "path_type" "ImplementationSpecific" -}}
  {{- $_ := set . "portal_path" "/*" -}}
  {{- $_ := set . "api_path" "/api/*" -}}
  {{- $_ := set . "service_path" "/service/*" -}}
  {{- $_ := set . "v2_path" "/v2/*" -}}
  {{- $_ := set . "controller_path" "/c/*" -}}
{{- else if eq $ingress.controller "ncp" }}
  {{- $_ := set . "path_type" "Prefix" -}}
  {{- $_ := set . "portal_path" "/.*" -}}
  {{- $_ := set . "api_path" "/api/.*" -}}
  {{- $_ := set . "service_path" "/service/.*" -}}
  {{- $_ := set . "v2_path" "/v2/.*" -}}
  {{- $_ := set . "controller_path" "/c/.*" -}}
{{- else }}
  {{- $_ := set . "path_type" "Prefix" -}}
  {{- $_ := set . "portal_path" "/" -}}
  {{- $_ := set . "api_path" "/api/" -}}
  {{- $_ := set . "service_path" "/service/" -}}
  {{- $_ := set . "v2_path" "/v2/" -}}
  {{- $_ := set . "controller_path" "/c/" -}}
{{- end }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "harbor.ingress" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
{{- if $ingress.labels }}
{{ toYaml $ingress.labels | indent 4 }}
{{- end }}
  annotations:
{{ toYaml $ingress.annotations | indent 4 }}
{{- if .Values.internalTLS.enabled }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
{{- end }}
{{- if eq $ingress.controller "ncp" }}
    ncp/use-regex: "true"
    {{- if $tls.enabled }}
    ncp/http-redirect: "true"
    {{- end }}
{{- end }}

spec:
{{- if $ingress.className }}
  ingressClassName: {{ $ingress.className }}
{{- end }}
{{- if $tls.enabled }}
  tls:
    - secretName: {{ template "harbor.tlsCoreSecretForIngress" . }}
      {{- if $ingress.hosts.core }}
      hosts:
        - {{ $ingress.hosts.core }}
      {{- end }}
{{- end }}
  rules:
    - host: {{ $ingress.hosts.core }}
      http:
        paths:
          - path: {{ .api_path }}
            pathType: {{ .path_type }}
            backend:
              service:
                name: {{ template "harbor.core" . }}
                port:
                  number: {{ template "harbor.core.servicePort" . }}
          - path: {{ .service_path }}
            pathType: {{ .path_type }}
            backend:
              service:
                name: {{ template "harbor.core" . }}
                port:
                  number: {{ template "harbor.core.servicePort" . }}
          - path: {{ .v2_path }}
            pathType: {{ .path_type }}
            backend:
              service:
                name: {{ template "harbor.core" . }}
                port:
                  number: {{ template "harbor.core.servicePort" . }}
          - path: {{ .controller_path }}
            pathType: {{ .path_type }}
            backend:
              service:
                name: {{ template "harbor.core" . }}
                port:
                  number: {{ template "harbor.core.servicePort" . }}
          - path: {{ .portal_path }}
            pathType: {{ .path_type }}
            backend:
              service:
                name: {{ template "harbor.portal" . }}
                port:
                  number: {{ template "harbor.portal.servicePort" . }}
{{- end }}
